---

- include_tasks: install.yml

- include_tasks: setup.yml

- name: check if ufw is installed
  command: dpkg -L ufw
  register: dpkg_ufw_check
  ignore_errors: yes

- include_tasks: ufw.yml
  when: dpkg_ufw_check.rc == 0

- include_tasks: config.yml
